name: Test Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          folder=${{ github.event.inputs.folder || 'tests' }}
          exclude=${{ github.event.inputs.exclude || '' }}
          find $folder -type f ! -path "$exclude" -name "*.py" -exec python -m unittest discover -s {} \;
